#!/bin/sh

echo "-----------------------------build go proto------------------------------"
PROTO_PATH="../../proto/"
PROTO_TLS="hello.proto"

function func_proto_path(){
    return $(${PROTO_PATH}${1}/${1}.proto)
}

echo "$(func_proto_path tls)"

echo "====build TLS===="
GRPC_TLS="../../tls/"
BIN_TLS_PATH="../../bin/tls/"

protoc --proto_path=${PROTO_PATH}/tls --go_out=plugins=grpc:${PROTO_PATH}/tls ${PROTO_PATH}/tls/${PROTO_TLS}
go build -o ${BIN_TLS_PATH}/client ${GRPC_TLS}/client/client.go
go build -o ${BIN_TLS_PATH}/server ${GRPC_TLS}/server/server.go

echo "====build TOKEN===="
GRPC_TLS="../../token/"
BIN_TLS_PATH="../../bin/token/"

protoc --proto_path=${PROTO_PATH}/token --go_out=plugins=grpc:${PROTO_PATH}/token ${PROTO_PATH}/token/${PROTO_TLS}
go build -o ${BIN_TLS_PATH}/client ${GRPC_TLS}/client/client.go
go build -o ${BIN_TLS_PATH}/server ${GRPC_TLS}/server/server.go

echo "====build interceptor===="
GRPC_TLS="../../interceptor/"
BIN_TLS_PATH="../../bin/interceptor/"

protoc --proto_path=${PROTO_PATH}/interceptor --go_out=plugins=grpc:${PROTO_PATH}/interceptor ${PROTO_PATH}/interceptor/${PROTO_TLS}
go build -o ${BIN_TLS_PATH}/client ${GRPC_TLS}/client/client.go
go build -o ${BIN_TLS_PATH}/server ${GRPC_TLS}/server/server.go